/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qtsshrodxtzcrxvpoczf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0c3Nocm9keHR6Y3J4dnBvY3pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk2MDMwODksImV4cCI6MjA5NTE3OTA4OX0.W114jai9nbJ4Jeq9qQcYZs7cV-Egm1QBw_W-GpK83vo"